source 'https://github.com/CocoaPods/Specs.git'   # <- Brug Git specs i stedet for CDN

platform :ios, '14.0'                             # vælg din minimum iOS-version
use_frameworks!

require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityInAppReview', :path => '../../node_modules/@capacitor-community/in-app-review'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
  pod 'CapacitorVoiceRecorder', :path => '../../node_modules/capacitor-voice-recorder'
end

target 'App' do
  capacitor_pods

  pod 'FirebaseCore'
  pod 'FirebaseAnalytics'
end

